image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
#  - build
  - package
  - deploy

#maven-build:
#  image: maven:3-jdk-8
#  stage: build
#  script: 
#  - "mvn package -B"
#  - "ls -l -h target/*.jar"
#  artifacts:
#    paths:
#      - "target/*.jar"

docker-build:
  stage: package
  image: docker:latest
  script:
  - docker version
  - docker build -t dockeryanxiao/actuator-sample .
  - docker login -u dockeryanxiao -p $CI_JOB_TOKEN hub.docker.com
  - docker push dockeryanxiao/actuator-sample

k8s-deploy-staging:
  image: google/cloud-sdk
  stage: deploy
  script:
  - echo "$GOOGLE_KEY" > key.json #Google Cloud service account key from Gcloud console
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-west1-a
  - gcloud config set project actuator-sample-205621
  - gcloud config unset container/use_client_certificate
  #- gcloud config set container/use_client_certificate True
  - gcloud container clusters get-credentials actuator-test #downloads the kubectl configuration file
  #- kubectl delete secret registry.gitlab.com
  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=juvestig --docker-password=$REGISTRY_PASSWD --docker-email=juvestig@gmail.com
  - kubectl apply -f deployment.yml
  environment:
    name: staging
    url: http://staging.example.com #Why?
  only:
  - master
