image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: 
  - "mvn package -B"
  - "ls -l -h target/*.jar"
  artifacts:
    paths:
      - "target/*.jar"

docker-build:
  tags:
  - docker
  stage: package
  script:
  - docker info
  - docker build -t dockeryanxiao/actuator-sample .
  - docker login -u dockeryanxiao -p $CI_BUILD_TOKEN
  - docker push dockeryanxiao/actuator-sample

k8s-deploy-staging:
  tags:
  - master-shell
  stage: deploy
  script:
  - kubectl apply -f deployment.yml
  environment:
    name: staging
    url: http://http://ingress.vicp.io #Why?
  only:
  - master
  
k8s-deploy-production:
 tags:
 - master-shell
 stage: deploy
 script:
 - kubectl apply -f deployment.yml -n prod
 environment:
  name: production
  url: http://http://ingress.vicp.io/root/actuator-sample
 when: manual
 only:
 - production
