apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actuator-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: actuator-test
    spec:
      containers:
      - name: actuator-sample
        image: dockeryanxiao/actuator-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
     # imagePullSecrets:
     #   - name: registry.gitlab.com
