apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actuator-test1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: actuator-test1
    spec:
      containers:
      - name: actuator-sample
        image: registry.gitlab.com/juvestig/actuator-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
